[package]
name = "MeiliFileFinder"
version = "0.1.0"
edition = "2021"

[dependencies]
meilisearch-sdk = "0.27.1"
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version="*",   features = ["derive"] }
serde_json = "*"

[dev-dependencies]
tempfile = "3.5"